import time

# Question:
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

LIMIT = 4000000

def main():
    start = time.clock()
    total = 0
    previousNumber = 1
    newNumber = 2
    while newNumber <= LIMIT:
        if newNumber % 2 == 0:
            total = total + newNumber
        newNumber = newNumber + previousNumber
        previousNumber = newNumber - previousNumber
    end = time.clock()
    print('answer: ' + str(total))
    print('time: ' + str(end - start))

if __name__ == '__main__':
    main()